Repository DFanso/commit-msg, pull requests merged in 2025-10, with the labels that each got.

#4 Added spinner
  go.mod
  go.sum
  src/main.go
Labels: hacktoberfest, hacktoberfest-accepted

#8 feat: add automatic clipboard copy functionality
  .gitignore
  README.md
  go.mod
  go.sum
  image.png
  src/main.go
Labels: hacktoberfest, hacktoberfest-accepted

#10 Refactor: Extract internal modules for better organization
  README.md
  src/internal/display/display.go
  src/internal/git/operations.go
  src/internal/stats/statistics.go
  src/internal/utils/utils.go
  src/main.go
Labels: hacktoberfest, hacktoberfest-accepted

#36 Handle non-200 status codes from Claude API
  src/claude/claude.go
Labels: bug, good first issue, hacktoberfest, go

#38 refactor: restructure project to follow Go conventions
  .github/workflows/build-and-release.yml
  CONTRIBUTING.md
  README.md
  assets/commit.gif
  assets/image.png
  cmd/commit-msg/main.go
  internal/chatgpt/chatgpt.go
  internal/claude/claude.go
  internal/display/display.go
  internal/gemini/gemini.go
  internal/git/operations.go
  internal/grok/grok.go
  internal/scrubber/scrubber.go
  internal/scrubber/scrubber_test.go
  internal/stats/statistics.go
  internal/utils/utils.go
  pkg/types/prompt.go
  pkg/types/types.go
Labels: enhancement, hacktoberfest

#40 Fix #39: Update Gemini API key references
  cmd/commit-msg/main.go
  internal/scrubber/scrubber.go
  internal/scrubber/scrubber_test.go
Labels: documentation, good first issue, hacktoberfest

#43 added ollama support for running local LLM's, Two new environment var…
  cmd/commit-msg/main.go
  go.mod
  go.sum
  internal/ollama/ollama.go
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, go

#46 Cli interface
  LICENSE
  cmd/cli/createMsg.go
  cmd/cli/llmSetup.go
  cmd/cli/root.go
  cmd/cli/store/store.go
  cmd/commit-msg/main.go
  go.mod
  go.sum
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, go

#51 updated README.md to include the ollama setup
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#64 Update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#65 Updated Readme for new CLI
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#67 Add thorough tests for git change detection and utils
  internal/git/operations_test.go
  internal/utils/utils_test.go
  pkg/types/types_test.go
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, go

#70 fix DFanso#52 : add Groq LLM support to setup and generation
  cmd/cli/createMsg.go
  cmd/cli/llmSetup.go
Labels: bug, hacktoberfest, hacktoberfest-accepted, go

#71 fix #69 : remove emojis from console output for professional appearance
  cmd/cli/createMsg.go
  internal/display/display.go
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, go

#75 Introduced a shared HTTP client with optimized settings
  internal/claude/claude.go
  internal/grok/grok.go
  internal/groq/groq.go
  internal/http/client.go
  internal/ollama/ollama.go
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted, go

#76 fix #72 : Replace hardcoded display limits with named constants in ShowFileStatistics
  internal/display/display.go
Labels: bug, enhancement, hacktoberfest, go

#83 Update header styles and .gitignore
  .gitignore
  cmd/cli/createMsg.go
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, go
